server:
  port: 8888

eureka:
  instance:
    hostname: localhost

spring:
  application:
    name: API-GateWay

  cloud:
    gateway:
      routes:
        - id: user-service
#          uri: lb://localhost
          uri: lb://user-service
          predicates:
            - Path=/user/**

        - id: contact-service
          uri: lb://contact-service
          predicates:
            - Path=/contact/**